#cloud-config

package_update: true
package_upgrade: true

packages:
- nginx

runcmd:
- systemctl enable nginx
- systemctl start nginx
- echo "<h1>Cloud-Init Deployment Successful!</h1>" > /usr/share/nginx/html/index.html